const acehController = require('../controllers/cuaca/acehController')
const baliController = require('../controllers/cuaca/baliController')
const bangkaBelitungController = require('../controllers/cuaca/bangkaBelitungController')
const bantenController = require('../controllers/cuaca/bantenController')
const bengkuluController = require('../controllers/cuaca/bengkuluController')
const dkiJakartaController = require('../controllers/cuaca/dkiJakartaController')
const gorontaloController = require('../controllers/cuaca/gorontaloController')
const jabarController = require('../controllers/cuaca/jabarController')
const jambiController = require('../controllers/cuaca/jambiController')
const jatengController = require('../controllers/cuaca/jatengController')
const jatimController = require('../controllers/cuaca/jatimController')
const kalbarController = require('../controllers/cuaca/kalbarController')
const kalselController = require('../controllers/cuaca/kalselController')
const kaltengController = require('../controllers/cuaca/kaltengController')
const kaltimController = require('../controllers/cuaca/kaltimController')
const kalutController = require('../controllers/cuaca/kalutController')
const kepRiauController = require('../controllers/cuaca/kepRiauController')
const lampungController = require('../controllers/cuaca/lampungController')
const malukuController = require('../controllers/cuaca/malukuController')
const malukuUtaraController = require('../controllers/cuaca/malukuUtaraController')
const ntbController = require('../controllers/cuaca/ntbController')
const nttController = require('../controllers/cuaca/nttController')
const papuaBaratController = require('../controllers/cuaca/papuaBaratController')
const papuaController = require('../controllers/cuaca/papuaController')
const riauController = require('../controllers/cuaca/riauController')
const sulbarController = require('../controllers/cuaca/sulbarController')
const sulselController = require('../controllers/cuaca/sulselController')
const sultengController = require('../controllers/cuaca/sultengController')
const sulutController = require('../controllers/cuaca/sulutController')
const yogyakartaController = require('../controllers/cuaca/yogyakartaController')
const sumbarController = require('../controllers/cuaca/sumbarController')
const sumselController = require('../controllers/cuaca/sumselController')
const sumutController = require('../controllers/cuaca/sumutController')
const sultenggaraController = require('../controllers/cuaca/sultenggaraController')

const router = require('express').Router()

router.get('/aceh', acehController)
router.get('/bali', baliController)
router.get('/bangka-belitung', bangkaBelitungController)
router.get('/banten', bantenController)
router.get('/bengkulu', bengkuluController)
router.get('/yogyakarta', yogyakartaController)
router.get('/dki-jakarta', dkiJakartaController)
router.get('/gorontalo', gorontaloController)
router.get('/jambi', jambiController)
router.get('/jawa-barat', jabarController)
router.get('/jawa-tengah', jatengController)
router.get('/jawa-timur', jatimController)
router.get('/kalimantan-barat', kalbarController)
router.get('/kalimantan-selatan', kalselController)
router.get('/kalimantan-tengah', kaltengController)
router.get('/kalimantan-timur', kaltimController)
router.get('/kalimantan-utara', kalutController)
router.get('/kepulauan-riau', kepRiauController)
router.get('/lampung', lampungController)
router.get('/maluku', malukuController)
router.get('/maluku-utara', malukuUtaraController)
router.get('/ntb', ntbController)
router.get('/ntt', nttController)
router.get('/papua', papuaController)
router.get('/papua-barat', papuaBaratController)
router.get('/riau', riauController)
router.get('/sulawesi-barat', sulbarController)
router.get('/sulawesi-selatan', sulselController)
router.get('/sulawesi-tengah', sultengController)
router.get('/sulawesi-tenggara', sultenggaraController)
router.get('/sulawesi-utara', sulutController)
router.get('/sumatera-barat', sumbarController)
router.get('/sumatera-selatan', sumselController)
router.get('/sumatera-utara', sumutController)

module.exports = router